package testing;

import java.io.File;

import java.util.LinkedList;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 * Clase que se ocupa de la parte visual de la aplicacion. Inlcuye el formateo
 * del código a HTML.
 *
 *
 *
 */
public class MainView extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLineasTotales = new javax.swing.JLabel();
        lblLineasComentario = new javax.swing.JLabel();
        lblLineasPorcentaje = new javax.swing.JLabel();
        lblComplejidad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMetodos = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelCodigo = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblArchivo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblFanIn = new javax.swing.JLabel();
        lblFanOut = new javax.swing.JLabel();
        lblLongitud = new javax.swing.JLabel();
        lblVolumen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Herramienta de Gestión de Testing");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jButton1.setText("Cargar archivo");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirFileChooser(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Resultados del análisis");

        lblLineasTotales.setBackground(new java.awt.Color(0, 0, 102));
        lblLineasTotales.setForeground(new java.awt.Color(255, 255, 255));
        lblLineasTotales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLineasTotales.setFocusTraversalPolicyProvider(true);
        lblLineasTotales.setOpaque(true);

        lblLineasComentario.setBackground(new java.awt.Color(0, 0, 102));
        lblLineasComentario.setForeground(new java.awt.Color(255, 255, 255));
        lblLineasComentario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLineasComentario.setFocusTraversalPolicyProvider(true);
        lblLineasComentario.setOpaque(true);
        lblLineasComentario.setPreferredSize(new java.awt.Dimension(40, 14));

        lblLineasPorcentaje.setBackground(new java.awt.Color(0, 0, 102));
        lblLineasPorcentaje.setForeground(new java.awt.Color(255, 255, 255));
        lblLineasPorcentaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLineasPorcentaje.setFocusTraversalPolicyProvider(true);
        lblLineasPorcentaje.setOpaque(true);
        lblLineasPorcentaje.setPreferredSize(new java.awt.Dimension(40, 14));

        lblComplejidad.setBackground(new java.awt.Color(0, 0, 102));
        lblComplejidad.setForeground(new java.awt.Color(255, 255, 255));
        lblComplejidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComplejidad.setFocusTraversalPolicyProvider(true);
        lblComplejidad.setOpaque(true);

        listaMetodos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Cargue un archivo Java para su análisis" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaMetodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccionMetodo(evt);
            }
        });
        listaMetodos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaMetodosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaMetodos);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("Código del método");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Métodos");

        labelCodigo.setEditable(false);
        labelCodigo.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(labelCodigo);

        jLabel2.setText("Cantidad de líneas de código");

        jLabel3.setText("Cantidad de líneas de comentarios");

        jLabel4.setText("Porcentaje de comentarios");

        jLabel5.setText("Complejidad Ciclomática");

        lblArchivo.setBackground(new java.awt.Color(0, 0, 102));
        lblArchivo.setForeground(new java.awt.Color(255, 255, 255));
        lblArchivo.setText("...");
        lblArchivo.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setText("Archivo");

        jLabel6.setText("Fan In");

        jLabel7.setText("Fan Out");

        jLabel8.setText("Longitud de Halstead");

        jLabel9.setText("Volúmen de Halstead");

        lblFanIn.setBackground(new java.awt.Color(0, 0, 102));
        lblFanIn.setForeground(new java.awt.Color(255, 255, 255));
        lblFanIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFanIn.setFocusTraversalPolicyProvider(true);
        lblFanIn.setOpaque(true);

        lblFanOut.setBackground(new java.awt.Color(0, 0, 102));
        lblFanOut.setForeground(new java.awt.Color(255, 255, 255));
        lblFanOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFanOut.setFocusTraversalPolicyProvider(true);
        lblFanOut.setOpaque(true);
        lblFanOut.setPreferredSize(new java.awt.Dimension(40, 14));

        lblLongitud.setBackground(new java.awt.Color(0, 0, 102));
        lblLongitud.setForeground(new java.awt.Color(255, 255, 255));
        lblLongitud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLongitud.setFocusTraversalPolicyProvider(true);
        lblLongitud.setOpaque(true);
        lblLongitud.setPreferredSize(new java.awt.Dimension(40, 14));

        lblVolumen.setBackground(new java.awt.Color(0, 0, 102));
        lblVolumen.setForeground(new java.awt.Color(255, 255, 255));
        lblVolumen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolumen.setFocusTraversalPolicyProvider(true);
        lblVolumen.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblLineasPorcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblLineasTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblLineasComentario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblComplejidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblLongitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblFanIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblFanOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLineasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLineasComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblLineasPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblComplejidad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFanIn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFanOut, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirFileChooser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirFileChooser

        FileFilter filter= new FileFilter() {

            @Override
            public boolean accept(File f) {
                return f.getName().toUpperCase().endsWith(".JAVA");
            }

            @Override
            public String getDescription() {
                return "Java files";
            }
        };
        fileChooser.setFileFilter(filter);
        int returnVal = fileChooser.showOpenDialog(MainView.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // Tomo el archivo seleccionado.
            this.file = fileChooser.getSelectedFile();
            DefaultListModel datosLista = new DefaultListModel();

            this.lblArchivo.setText(this.file.getName());
            
            if (!this.file.getName().toUpperCase().endsWith(".JAVA")) {
                datosLista.add(0, "El archivo no pudo ser procesado.");
            } else {
                int i = 0;
                //Obtengo los métodos del programa.
                this.metodos = Analizador.analizarMetodos(this.file);

                // Recorro la lista de metodos para agregarlos al modelo.                
                for (Metodo metodo : metodos) {
                    datosLista.add(i++, metodo);
                }
            }

            // Seteo el modelo a la lista.
            this.listaMetodos.setModel(datosLista);

        }

    }//GEN-LAST:event_abrirFileChooser

    private void procesarSeleccionMetodo(){
        if("Cargue un archivo Java para su análisis".equals(this.listaMetodos.getSelectedValue()))
            return;
        
        Metodo metodo = Analizador.analizarMetodo(this.file, this.listaMetodos.getSelectedValue());

        /* Muestro la cantidad de lineas de codigo */
        this.lblLineasTotales.setText(String.valueOf(metodo.getLineasCodigo()));
        
        /* Muestro la cantidad de lineas de comentarios */
        this.lblLineasComentario.setText(String.valueOf(metodo.getLineasComentario()));

        /* Muestro la razon entre comentarios y codigo */
        this.lblLineasPorcentaje.setText(metodo.getPorcentaje());

        /* Muestro la complejiadd ciclomatica */
        this.lblComplejidad.setText(String.valueOf(metodo.getComplejidadCiclomatica()));
        
        this.lblFanIn.setText(String.valueOf(metodo.getFanIn()));
        
        this.lblFanOut.setText(String.valueOf(metodo.getFanOut()));
        
        this.lblLongitud.setText(String.valueOf(metodo.gethLongitud()));
        
        this.lblVolumen.setText(String.valueOf(metodo.gethVolumen()));

        // Preparo el codigo para mostrar.
        String codigoResaltado = metodo.getCodigo();

        this.labelCodigo.setText(codigoResaltado);
    }
    
    private void seleccionMetodo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionMetodo
        procesarSeleccionMetodo();
        

    }//GEN-LAST:event_seleccionMetodo

    private void listaMetodosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaMetodosValueChanged
        procesarSeleccionMetodo();
    }//GEN-LAST:event_listaMetodosValueChanged
    /**
     * @param args the command line arguments
     *
     * public static void main(String args[]) { /* Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
     try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the form 
     }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane labelCodigo;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblComplejidad;
    private javax.swing.JLabel lblFanIn;
    private javax.swing.JLabel lblFanOut;
    private javax.swing.JLabel lblLineasComentario;
    private javax.swing.JLabel lblLineasPorcentaje;
    private javax.swing.JLabel lblLineasTotales;
    private javax.swing.JLabel lblLongitud;
    private javax.swing.JLabel lblVolumen;
    private javax.swing.JList listaMetodos;
    // End of variables declaration//GEN-END:variables
    private File file;
    private LinkedList<Metodo> metodos;

    @Override
    public void run() {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

//                System.out.println(info.getName());

                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Mostrar.
        this.setVisible(true);
        this.setLocationRelativeTo(null); 
    }
}
